### ISSUE TITLE
Communicate code editor info with other components

### ISSUE THREAD

**Issue by LvlAndFarm** [LvlAndFarm/python-editor-v3#1]
## Depends on

Other tickets:

- N/A

Third parties:

- N/A

## Description

We have an existing proof of concept on the `widgets` branch for an extension that can render widgets for us. We need to make use of `syntaxTree` to extract information about the current line (or block) of code. This should enable us to dynamically render different widgets, either inline or on the sidebar if we decide to go that way. 

## Todo

- [ ] Decide what information need to be shared (E.g. if we only need information about the current line with a few options: `ASSIGNMENT`, `FUNCTION_CALL` and some additional parameters etc)
- [ ] Add a React Context to share information with other React components
- [ ] Design a couple of widgets to showcase the feature
- [ ] Implement an extension to CodeMirror that extracts the required information
