### ISSUE TITLE
Create sidebar tab

### ISSUE THREAD

**Issue by Stazi-101** [LvlAndFarm/python-editor-v3#6]
## Description

Our plan for code interaction requires a new tab in the sidebar with UI elements corresponding to parameters of a selected function. This will be linked to the code separately, but initially can be set up with examples to build off.

## Todo

- [x] Create tab by copying another
- [x] Separate from other tabs
- [~] Change icon
- [x] Add example sliders and fields corresponding to parameters
- [x] Format prettily
- [x] Separate into pages
- [ ] Generalise generating pages for a function
- [ ] Add more functions
